/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testNormalOperations() {
        Account account = new Account();
        account.deposit(1);
        assertEquals(1, account.getBalance());
        account.withdraw(1);
        assertEquals(0, account.getBalance());
    }

    @Test
    public void testThreadSafety() {
        Account account = new Account();
        Thread depositThread = new Thread(() -> {
            for (int i = 0; i < 1000; i++) {
                account.safeDeposit(1);
            }
        });
        Thread withdrawThread = new Thread(() -> {
            for (int i = 0; i < 1000; i++) {
                account.safeWithdraw(1);
            }
        });
        depositThread.start();
        withdrawThread.start();
        try {
            depositThread.join();
            withdrawThread.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        assertEquals(0, account.getBalance());
    }

    @Test
    public void testBarrier() {
        BarrierExample.main(null);
        assertEquals(0, BarrierExample.finalBalance);
    }

    @Test
    public void testLatch() {
        LatchExample.main(null);
        assertEquals(0, LatchExample.finalBalance);
    }
}
